# Generated by Django 2.2.3 on 2019-07-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDiscipline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipeP', models.CharField(max_length=100)),
                ('scoreP', models.IntegerField(max_length=2)),
                ('equipeA', models.CharField(max_length=100)),
                ('scoreA', models.IntegerField(max_length=2)),
                ('jouer', models.IntegerField(default=0, max_length=1)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Paris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipeP', models.CharField(max_length=100)),
                ('scoreP', models.IntegerField()),
                ('equipeA', models.CharField(max_length=100)),
                ('scoreA', models.IntegerField(max_length=2)),
                ('gagner', models.IntegerField(default=0, max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEquipe', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipeimg')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Discipline')),
            ],
        ),
    ]
