# Generated by Django 2.2.3 on 2019-07-29 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190729_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='equipeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipeA', to='page.Equipes'),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipeP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipeP', to='page.Equipes'),
        ),
    ]
