# Generated by Django 2.2.3 on 2019-07-31 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190729_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipes',
            new_name='Equipe',
        ),
        migrations.AddField(
            model_name='match',
            name='heure',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='heure et jour du match'),
        ),
        migrations.AddField(
            model_name='match',
            name='utilisateur',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='paris',
            name='utilisateur',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='paris',
            name='equipeA',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='paris',
            name='equipeP',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
