# Generated by Django 2.2.3 on 2019-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='paris',
            name='mise',
            field=models.FloatField(default=0),
        ),
    ]
