# Generated by Django 2.2.3 on 2019-08-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20190801_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paris',
            name='utilisateur',
            field=models.IntegerField(),
        ),
    ]
